apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - name: nginxcontainer
      image: nginx:1.25.5
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
      securityContext:
        seccompProfile:
          type: RuntimeDefault